development:
  adapter: mysql2
  encoding: utf8
  database: coffee_app_development
  pool: 5
  username: karirin
  password: karirin3948
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: coffee_app_test
  pool: 5
  username: karirin
  password: karirin3948
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: coffee_app_production
  pool: 5
  username: root
  password: 
